### ISSUE TITLE
about apn

### ISSUE THREAD

**Issue by narrowsnap** [jeong-tae/RACNN-pytorch#15]
### All the crop operate can description with a 2x3 matrix([[0.5, 0.0, 0.0], [0.0, 0.5, 0.0]]).
![selection_052](https://user-images.githubusercontent.com/17559987/50140208-eafdaf00-02de-11e9-9e1e-0dc3da794a37.png)

### M00 and M11 mean the size of crop area, M02 and M12 mean the coordinate of crop area. 
![selection_053](https://user-images.githubusercontent.com/17559987/50140496-dc63c780-02df-11e9-875d-ffd8354dc0cf.png)
### Which means we only need to train 2 parameter(M02 and M12) to find the attention area.
![selection_054](https://user-images.githubusercontent.com/17559987/50140672-83e0fa00-02e0-11e9-91e5-fb12ff6d2161.png)

### Hope this can help you!

**Comment by jeong-tae** [comment]
Thank you for sharing. The reason why I implement this is only for understanding more about paper. If I can't reproduce performance same as write in the paper, which means that there is still missing to understand fully.

I know this repository become more getting interest but still busy these days. Anyway, thank you for the sharing and I will figure out the reason to reproduce this someday!
