### ISSUE TITLE
about saving the tx ty tl

### ISSUE THREAD

**Issue by Yanyyy** [jeong-tae/RACNN-pytorch#16]
Hi, I'm interested about RACNN and your code. But I‘m not familiar with pytorch. I want to ask how could I save the tx, ty and tl and use them to get the pics which is the input of the second channel and the third channel? Thank you!

**Comment by jeong-tae** [comment]
Sorry I didn't get your intention exactly.
Maybe... this code will help you to understand
https://github.com/jeong-tae/RACNN-pytorch/blob/master/models/RACNN.py#L85-L10
