### ISSUE TITLE
Hello author, I would like to ask the two documents in the picture you have given in the project? I can't find these two files in the downloaded resource.

### ISSUE THREAD

**Issue by rechealzrq** [jeong-tae/RACNN-pytorch#17]
[图片][图片]

**Comment by rechealzrq** [comment]
![FPA_S_~ZYMA(OUF0RE`J(1](https://user-images.githubusercontent.com/43806648/67614794-6c727780-f7f5-11e9-82e8-099d58df1e89.png)
![FG}D_HZST5RHL{21L5D7M93](https://user-images.githubusercontent.com/43806648/67614795-71372b80-f7f5-11e9-92c1-614a6c605818.png)

**Comment by jtlee90** [comment]
you guys need to download those files from data provider.
