### ISSUE TITLE
RuntimeError: _th_exp_out not supported on CUDAType for Long

### ISSUE THREAD

**Issue by miss1997yuan** [jeong-tae/RACNN-pytorch#18]
is there someone meet the same problem ?

**Comment by Pythonisfun** [comment]
i have the same problem,have you solved it?

**Comment by pshroff04** [comment]
May be little late here. Line 75 in RACNN.py:  
` h = lambda x: 1 / (1 + torch.exp(-10 * x))` 
to 
` h = lambda x: 1 / (1 + torch.exp(-10. * x))`
(10.)
