### ISSUE TITLE
RuntimeError: It is expected output_size equals to 1, but got size 2

### ISSUE THREAD

**Issue by miss1997yuan** [jeong-tae/RACNN-pytorch#19]

**Comment by jeong-tae** [comment]
Need more detailed explanation here. When did you face this error?

**Comment by cpluspluser** [comment]
i have the same problem.

**Comment by MichaelUhh** [comment]
Hello, I have the same issue:
RuntimeError: It is expected output_size equals to 1, but got size 3,
when using `torch.nn.functional.interpolate `.
It is certainly due to a misunderstanding on how to use the parameter 'dim'.

here is a sample of code, building a grad_CAM with vgg16 on MNIST:

`def get_Grad_CAM(index):
    img = dataset[index][0].view(1, 3, 224, 224)
    vgg_model = VGG_Grad_CAM()
    output = vgg_model(img)
    values, indices = torch.topk(output, 3)
    
    for indice in indices[0]:
        output[:, indice].backward()
        gradients = vgg_model.get_activations_gradient()
        activations = vgg_model.get_activations(img).detach()
        
        pooled_gradients = torch.mean(gradients, dim=[0, 2, 3])
        
        for i in range(512):
            activations[:, i, :, :] *= pooled_gradients[i]
            
        heatmap = torch.mean(activations, dim=1).squeeze()
        heatmap = np.maximum(heatmap, 0)
        heatmap /= torch.max(heatmap)
        plt.matshow(heatmap.squeeze())
        
        resized_heatmap = torch.nn.functional.upsample_nearest(
            heatmap.unsqueeze_(0), size=(1, 224, 224), scale_factor=None)
    
        
        return gradients, activations, pooled_gradients, heatmap, resized_heatmap`
