### ISSUE TITLE
is there some bug

### ISSUE THREAD

**Issue by miss1997yuan** [jeong-tae/RACNN-pytorch#20]
when i run the trainer.py,there is no problem in pre_apn_epoch,but when test ,it is out of size ,just like the figure ,what i use is a GT2010 Ti,have no idea of the problem ,is there any tensor space not be released?

**Comment by miss1997yuan** [comment]
![1572489902(1)](https://user-images.githubusercontent.com/30165188/67914613-98ae3f80-fbcb-11e9-8250-2a699a7ca1a8.jpg)

**Comment by tobelyf** [comment]
I also encoutered the same problem as you, and there are many tips in this webpage(https://blog.csdn.net/qq_28660035/article/details/80688427) to reduce memory usage, Hope to help you a little.
