### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by liujiale1234** [jeong-tae/RACNN-pytorch#21]
Traceback (most recent call last):
  File "trainer.py", line 306, in <module>
    train()
  File "trainer.py", line 57, in train
    trainset = CUB200_loader(os.getcwd() + 'G:/RACNN-pytorch-master/RACNN-pytorch-master/data/CUB_200_2011/images', split = 'train')
TypeError: 'module' object is not callable

I need help

**Comment by jeong-tae** [comment]
Maybe given path is incorrect. Sorry for late reply.
