### ISSUE TITLE
Use of Average Pool to Conv5_4 layers before APN?

### ISSUE THREAD

**Issue by pshroff04** [jeong-tae/RACNN-pytorch#24]
Hi ,

Can you please tell the use of  average pooling over the feature map of conv5_4? I couldn't find its reference in paper? @jeong-tae @jtlee90

Thanks

**Comment by jtlee90** [comment]
Thank you for reaching me!

Well... I made this code long time ago... so I am not sure that why I am pooling over the feature map of conv5_4.

I remember that I followed original implementation of RACNN, which rewritten in... maybe caffe?
Yes, yes, I saw some code, *.proto from original implementation and implement into pytorch code!

Also, in the paper section 3.4, they mention conv5_4 as highest response map and last conv layer in vgg to consider squares. Maybe that's the exact reason.

**Comment by pshroff04** [comment]
Thanks for the response!

Yes, if layers are corresponding to their caffe implementation, that does make senses. 

Also, I had a thought regarding the pre-training APN network. Should we keep the parameters of VGG fixed and train the parameters corresponding to APN layers only? since pre-training aims only to learn function to transform feature maps (conv5_4) to  [tx,ty,tl]. 

Please let me knows your view on this?

**Comment by jeong-tae** [comment]
I guess... yes. That's the alternative training for two network.
and I think if APN already propose good enough attention, you don't need to train APN anymore.

but maybe there will be small rooms to improve attention more.
