### ISSUE TITLE
How about your experiment results now?

### ISSUE THREAD

**Issue by Xingxu1996** [jeong-tae/RACNN-pytorch#5]
Hi, I'm interested in racnn and your code. How about your experiment results now? Is it worked well now?

**Comment by fxle** [comment]
Hello,I'm also very interested in your experiment.how about it now? What parts of  your plan have been completed?

**Comment by jeong-tae** [comment]
still no progress. sorry!

**Comment by jeong-tae** [comment]
As this repository getting attentions of you, I feel some responsibility to provide exact and detailed results of this experiments.

But still I am busy to work with other projects and my interests in this is low. I hope that I can provide good reproduction
