### ISSUE TITLE
about data and what those .txt file contain 

### ISSUE THREAD

**Issue by longgang123** [jeong-tae/RACNN-pytorch#8]
in the cub_loader train_test_split.txt classes.txt images.txt image_class_labels.txt been used. will U please tell me what each file look like and what's have in it.

**Comment by longgang123** [comment]
in the cub_loader train_test_split.txt classes.txt images.txt image_class_labels.txt been used. will U please tell me what each file look like and what's have in it.

**Comment by jeong-tae** [comment]
Dataset are available from http://www.vision.caltech.edu/visipedia/CUB-200-2011.html

**Comment by jeong-tae** [comment]
You need to implement data loader own yourself.
Or you can prepare your dataset like CUB, but locate your data and classes
